version: '3.1'
services:
  backend:
    build: ./backend
    ports: 
      - "5000:5000"
    links:
      - db

  frontend:
    build: ./frontend/pms-client
    ports: 
      - "8080:8080"
    links:
      - backend

  db:
    build: ./db
